name: Auto-upload HTML page

on:
  schedule:
    - cron: */01 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: node index.js
