on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy index.html from the branch that triggered the workflow to the gh-pages branch
        run: git checkout ${{ github.event.workflow_run.branch }} -- public/index.html
      - name: Deploy to GitHub Pages
        uses: actions/gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public