on:
  schedule:
    - cron: */10 * * * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          branch: gh-pages
          path: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
