on:
  workflow_dispatch:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Change permissions on public directory
        run: chmod -R 777 public/
      - run: npm run build
      - name: Set Git username and email address
        run: |
          git config --global --add safe.directory /__w/workflow-experiment/workflow-experiment
          git config --global user.name "Jacob Louis"
          git config --global user.email "jacob@bluelotusmedia.com"
      - name: Commit index.html file
        run: git add public/index.html && git commit -m 'Committing index.html file'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy index.html from main branch to gh-pages branch
        run: git checkout main -- public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
