on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Change permissions on public directory
        run: chmod -R 777 public/
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy index.html from main branch to gh-pages branch
        run: git checkout main -- public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public