on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check permissions of public directory
        run: sudo ls -l public/
      - name: Set permissions of public directory
        run: sudo chmod 755 public/
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy index.html from main branch to gh-pages branch
        run: git checkout main -- public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public