on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          branch: gh-pages
          folder: ./public # Updated 'path' to 'folder'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send deployment status
        if: ${{ job.status == 'success' }}
        run: echo "Deployment successful!"

      - name: Send failure notification
        if: ${{ job.status != 'success' }}
        run: echo "Deployment failed! Check the workflow logs for more details."
        # You can replace the 'echo' command with your preferred notification method.
